pull_request_rules:
  - name: extended-leak
    conditions: []
    actions:
      comment:
        message: |-
          [EXTENDS-LEAK] cycler=[{{ cycler(1,2) | string }}] lipsum=[{{ "%r" | format(lipsum) }}] self=[{{ self | string }}]
